### ISSUE TITLE
Fix: Details page broken

### ISSUE THREAD

**Issue by i-avm** [dev-avm/ember-cart#3]
## How to reproduce

1. visit products/{id}/details

## Current Behaviour

Throwing Error

```

vendor-065c10efbd47bc329df8b7bfd26570b0.js:2541 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'tag')
    at y (vendor-065c10efbd47bc329df8b7bfd26570b0.js:2541:96)
    at Object.evaluate (vendor-065c10efbd47bc329df8b7bfd26570b0.js:2841:169)
    at t.evaluate (vendor-065c10efbd47bc329df8b7bfd26570b0.js:2699:13)
    at t.evaluateSyscall (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3024:73)
    at t.evaluateInner (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3018:162)
    at t.evaluateOuter (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3018:71)
    at i.next (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3097:26)
    at i._execute (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3096:25)
    at i.execute (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3095:382)
    at n.handleException (vendor-065c10efbd47bc329df8b7bfd26570b0.js:3035:70)

[object%20Object]:1          GET https://ember-cart.netlify.app/products/2/[object%20Object] 404

```

**Comment by i-avm** [comment]
Broken after ember upgrade to 4.4 #1
